### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by tshemsedinov** [vladlinu/Voicy#2]
- [x] Need 1-2 page README file (dependencies, environment and requirements, howto, etc.)
- [x] Do you use linter?
- [x] Is it ok to commit `__pycache__` to repo?
- [x] Will be great to have CI, for example https://travis-ci.org/ it's easy to setup and free for open source projects

**Comment by VladyslavHolik** [comment]
All troubles have solved, i used pylint as linter, deleted __pycache__, and signed up on travis ci
